server:
  port: 9011
spring:
  datasource:
    name: mall
    url: jdbc:mysql://192.168.10.132:3306/mall?autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useSSL=false
    password: Y1!UtFOhAs%2
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

aaa: 李四-product-test